// Wedding invite — sent to a NEW user attached to a wedding. Carries the signup/invite
// action link generated by inviteUserToWedding.

import { renderLayout } from '../layout.ts';
import { button, divider, esc, eyebrow, heading, infoCard, note, paragraph, urlFallback } from '../components.ts';

interface Data {
  inviterName?: string;
  weddingName?: string;
  roleLabel?: string;
  actionUrl?: string;
  recipientEmail?: string;
}

export function subject(d: Data): string {
  const w = d.weddingName || 'החתונה';
  return `הוזמנתם לתכנן את ${w} ב-WedFlow`;
}

export function html(d: Data): string {
  const inviter = esc(d.inviterName || 'מארגן/ת החתונה');
  const wedding = esc(d.weddingName || 'החתונה');
  const url = d.actionUrl || '#';

  const content = `
    ${eyebrow('הזמנה')}
    ${heading('הוזמנתם לתכנן חתונה')}
    ${paragraph(`<strong data-t="ink" style="color:inherit;">${inviter}</strong> הזמין/ה אתכם להצטרף לתכנון של <strong data-t="ink" style="color:inherit;">${wedding}</strong> ב-WedFlow — המקום שבו כל פרטי החתונה חיים יחד: רשימת המוזמנים, סידורי ההושבה, הספקים, התקציב והלוחות זמנים.`)}
    ${infoCard([
      { label: 'החתונה', value: d.weddingName || 'החתונה' },
      { label: 'התפקיד שלכם', value: d.roleLabel || 'בן/בת משפחה' },
    ])}
    ${divider()}
    <div style="text-align:center;">
      ${button('קבלת ההזמנה', url)}
    </div>
    ${note('הקישור מפעיל את החשבון שלכם ומצרף אתכם לחתונה. אם לא ציפיתם להזמנה הזו, אפשר פשוט להתעלם מהמייל.')}
    ${urlFallback(url)}
  `;

  return renderLayout({
    preheader: `${d.inviterName ? inviter : 'מישהו'} מזמין/ה אתכם לתכנן את ${wedding} יחד`,
    content,
  });
}

export function text(d: Data): string {
  const inviter = d.inviterName || 'מארגן/ת החתונה';
  const wedding = d.weddingName || 'החתונה';
  const role = d.roleLabel || 'בן/בת משפחה';
  return [
    `הוזמנתם לתכנן את ${wedding} ב-WedFlow`,
    ``,
    `${inviter} הזמין/ה אתכם להצטרף לתכנון של ${wedding}.`,
    `התפקיד שלכם: ${role}`,
    ``,
    `קבלת ההזמנה:`,
    d.actionUrl || '',
    ``,
    `אם לא ציפיתם להזמנה הזו, אפשר להתעלם מהמייל.`,
    `— WedFlow`,
  ].join('\n');
}
